;;; noir-theme.el --- Monochrome dark theme, Tonsky-flavored Lackluster port -*- lexical-binding: t; -*-
;;
;; Palette derived from slugbyte/lackluster.nvim (MIT, Slugbyte).
;; Color usage informed by https://tonsky.me/blog/syntax-highlighting/.
;;
;; SPDX-License-Identifier: MIT

;;; Commentary:
;; True-black backdrop. Highlights reserved for declarations and constants;
;; keywords, calls, and variable usages inherit the default face. Comments
;; are bright (yellow), not dimmed. Punctuation is greyed out.

;;; Code:

(deftheme noir "Monochrome dark theme; few colors, used on purpose.")

(let ((bg            "#000000")
      (bg-menu       "#0a0a0a")
      (bg-popup      "#0c0c0c")
      (bg-statusln   "#161616")
      (bg-whitespace "#121212")
      (gray1         "#080808")
      (gray2         "#191919")
      (gray3         "#2a2a2a")
      (gray4         "#444444")
      (gray5         "#555555")
      (gray6         "#7a7a7a")
      (gray7         "#aaaaaa")
      (gray8         "#cccccc")
      (lack          "#708090")
      (luster        "#deeeed")
      (orange        "#ffaa88")
      (yellow        "#abab77")
      (green         "#789978")
      (blue          "#7788aa")
      (red           "#d70000"))

  (custom-theme-set-faces
   'noir

   ;; ---- Core ----
   `(default              ((t (:foreground ,luster :background ,bg))))
   `(cursor               ((t (:background ,luster))))
   `(fringe               ((t (:foreground ,gray4 :background ,bg))))
   `(vertical-border      ((t (:foreground ,gray3 :background ,bg))))
   `(window-divider       ((t (:foreground ,gray3))))
   `(window-divider-first-pixel ((t (:foreground ,gray3))))
   `(window-divider-last-pixel  ((t (:foreground ,gray3))))
   `(region               ((t (:foreground ,bg :background ,gray8 :extend t))))
   `(secondary-selection  ((t (:background ,gray3 :extend t))))
   `(highlight            ((t (:background ,gray1))))
   `(hl-line              ((t (:background ,gray1 :extend t))))
   `(shadow               ((t (:foreground ,gray4))))
   `(trailing-whitespace  ((t (:background ,bg-whitespace))))
   `(whitespace-trailing  ((t (:background ,bg-whitespace))))
   `(whitespace-tab       ((t (:foreground ,gray3))))
   `(whitespace-space     ((t (:foreground ,gray3))))
   `(whitespace-newline   ((t (:foreground ,gray3))))

   ;; ---- Line numbers ----
   `(line-number              ((t (:foreground ,gray4 :background ,bg))))
   `(line-number-current-line ((t (:foreground ,gray7 :background ,bg :weight normal))))
   `(line-number-major-tick   ((t (:foreground ,gray5 :background ,bg))))
   `(line-number-minor-tick   ((t (:foreground ,gray4 :background ,bg))))

   ;; ---- Modeline ----
   `(mode-line            ((t (:foreground ,gray8 :background ,bg-statusln :box nil))))
   `(mode-line-inactive   ((t (:foreground ,gray5 :background ,gray1 :box nil))))
   `(mode-line-buffer-id  ((t (:foreground ,luster :weight normal))))
   `(mode-line-emphasis   ((t (:foreground ,luster))))
   `(mode-line-highlight  ((t (:background ,gray3 :box nil))))
   `(euler-mode-line-state     ((t (:foreground ,luster :weight bold))))
   `(euler-mode-line-muted     ((t (:foreground ,gray6))))
   `(euler-mode-line-modified  ((t (:foreground ,orange :weight bold))))
   `(euler-mode-line-read-only ((t (:foreground ,gray6))))
   `(euler-mode-line-position  ((t (:foreground ,gray7))))

   ;; ---- Minibuffer + link + status semantics ----
   `(minibuffer-prompt    ((t (:foreground ,luster))))
   `(link                 ((t (:foreground ,lack :underline t))))
   `(link-visited         ((t (:foreground ,gray6 :underline t))))
    `(button               ((t (:inherit link))))
    `(error                ((t (:foreground ,red :weight bold))))
    `(warning              ((t (:foreground ,orange))))
    `(success              ((t (:foreground ,green))))
    `(match                ((t (:foreground ,bg :background ,gray8))))
    `(completions-annotations ((t (:foreground ,gray6))))
    `(completions-common-part ((t (:foreground ,luster :weight bold))))
    `(completions-first-difference ((t (:foreground ,lack :weight bold))))
    `(completions-group-title ((t (:foreground ,gray6 :weight bold))))
    `(completions-group-separator ((t (:foreground ,gray3 :strike-through ,gray3))))

   ;; ---- Header line / tooltip placeholders (fleshed out later) ----
   `(header-line          ((t (:foreground ,gray7 :background ,bg-statusln :box nil))))
   `(tooltip              ((t (:foreground ,gray8 :background ,bg-popup))))

   ;; ---- Font-lock: Tonsky-applied ----
   ;; Don't highlight keywords / calls / usages.
   `(font-lock-keyword-face            ((t (:inherit default))))
   `(font-lock-builtin-face            ((t (:inherit default))))
   `(font-lock-preprocessor-face       ((t (:inherit default))))
   `(font-lock-function-call-face      ((t (:inherit default))))
   `(font-lock-variable-use-face       ((t (:inherit default))))
   `(font-lock-property-use-face       ((t (:inherit default))))

    ;; Declarations — hierarchy by weight/slant first, hue second.
    `(font-lock-variable-name-face      ((t (:foreground ,blue))))
    `(font-lock-function-name-face      ((t (:inherit font-lock-variable-name-face))))
    `(font-lock-property-name-face      ((t (:foreground ,gray8))))
    `(font-lock-type-face               ((t (:foreground ,gray7 :slant italic))))

    ;; Constants — literals stay greyscale; green is semantic success only.
    `(font-lock-string-face             ((t (:foreground ,gray7))))
    `(font-lock-number-face             ((t (:foreground ,gray6))))
    `(font-lock-constant-face           ((t (:foreground ,gray7 :weight bold))))
    `(font-lock-regexp-face             ((t (:foreground ,gray7 :slant italic))))
    `(font-lock-escape-face             ((t (:foreground ,gray8 :weight bold))))
    `(font-lock-regexp-grouping-construct ((t (:foreground ,gray6))))
    `(font-lock-regexp-grouping-backslash ((t (:foreground ,gray6))))

   ;; Comments — bright yellow (Tonsky).
   `(font-lock-comment-face            ((t (:foreground ,yellow))))
   `(font-lock-comment-delimiter-face  ((t (:foreground ,yellow))))
   `(font-lock-doc-face                ((t (:foreground ,yellow))))
   `(font-lock-doc-markup-face         ((t (:foreground ,yellow))))

   ;; Punctuation greyed.
    `(font-lock-punctuation-face        ((t (:foreground ,gray5))))
    `(font-lock-bracket-face            ((t (:foreground ,gray5))))
    `(font-lock-delimiter-face          ((t (:foreground ,gray5))))
    `(font-lock-operator-face           ((t (:foreground ,gray5))))
    `(font-lock-misc-punctuation-face   ((t (:foreground ,gray5))))
    `(font-lock-negation-char-face      ((t (:foreground ,gray5))))

   ;; Reserve red for actual warning sentinels (signal, deprecated, etc.).
   `(font-lock-warning-face            ((t (:foreground ,red :weight bold))))

   ;; ---- nix-mode (non-treesit) custom faces ----
   `(nix-keyword-face                  ((t (:inherit default))))
   `(nix-keyword-warning-face          ((t (:inherit font-lock-warning-face))))
   `(nix-builtin-face                  ((t (:inherit default))))
   `(nix-constant-face                 ((t (:inherit font-lock-constant-face))))
    `(nix-attribute-face                ((t (:inherit font-lock-variable-name-face))))
    `(nix-antiquote-face                ((t (:inherit font-lock-punctuation-face))))
    `(nix-escape-face                   ((t (:inherit font-lock-escape-face))))
    `(nix-store-path-face               ((t (:foreground ,gray6))))
    `(nix-store-path-realised-face      ((t (:foreground ,gray6))))
    `(nix-store-path-unrealised-face    ((t (:foreground ,orange))))
    `(nix-search-pname                  ((t (:foreground ,luster :weight bold))))
    `(nix-search-version                ((t (:foreground ,gray6))))
    `(nix-search-description            ((t (:foreground ,gray7))))

   ;; ---- Vertico ----
    `(vertico-current                   ((t (:background ,gray3 :extend t))))
    `(vertico-group-title               ((t (:foreground ,gray6 :weight normal))))
    `(vertico-group-separator           ((t (:foreground ,gray3 :strike-through ,gray3))))
    `(vertico-multiline                 ((t (:foreground ,gray6))))
    `(vertico-indexed                   ((t (:foreground ,gray5))))
    `(vertico-mouse                     ((t (:background ,gray2))))
    `(vertico-quick1                    ((t (:foreground ,bg :background ,lack :weight bold))))
    `(vertico-quick2                    ((t (:foreground ,bg :background ,gray7 :weight bold))))

   ;; ---- Corfu (popup completion) ----
   `(corfu-default                     ((t (:background ,bg-menu :foreground ,gray8))))
   `(corfu-current                     ((t (:background ,gray3 :foreground ,luster))))
   `(corfu-border                      ((t (:background ,gray3))))
   `(corfu-bar                         ((t (:background ,gray5))))
   `(corfu-deprecated                  ((t (:foreground ,gray5 :strike-through t))))
    `(corfu-annotations                 ((t (:foreground ,gray6))))
    `(corfu-popupinfo                   ((t (:background ,bg-popup :foreground ,gray8))))
    `(corfu-echo                        ((t (:foreground ,gray6))))
    `(corfu-indexed                     ((t (:foreground ,gray5))))
    `(corfu-quick1                      ((t (:foreground ,bg :background ,lack :weight bold))))
    `(corfu-quick2                      ((t (:foreground ,bg :background ,gray7 :weight bold))))

   ;; ---- Marginalia (annotations) ----
   `(marginalia-key                    ((t (:foreground ,lack))))
   `(marginalia-documentation          ((t (:foreground ,gray6))))
   `(marginalia-file-name              ((t (:foreground ,gray7))))
   `(marginalia-file-priv-dir          ((t (:foreground ,lack))))
   `(marginalia-file-priv-link         ((t (:foreground ,lack))))
   `(marginalia-file-priv-read         ((t (:foreground ,gray7))))
   `(marginalia-file-priv-write        ((t (:foreground ,gray6))))
   `(marginalia-file-priv-exec         ((t (:foreground ,green))))
   `(marginalia-file-priv-other        ((t (:foreground ,gray5))))
   `(marginalia-file-priv-no           ((t (:foreground ,gray4))))
   `(marginalia-file-owner             ((t (:foreground ,gray6))))
   `(marginalia-modified               ((t (:foreground ,orange))))
   `(marginalia-date                   ((t (:foreground ,gray6))))
   `(marginalia-size                   ((t (:foreground ,gray7))))
   `(marginalia-number                 ((t (:foreground ,gray7))))
    `(marginalia-string                 ((t (:foreground ,gray7))))
   `(marginalia-symbol                 ((t (:foreground ,gray7))))
   `(marginalia-mode                   ((t (:foreground ,gray7))))
   `(marginalia-on                     ((t (:foreground ,green))))
   `(marginalia-off                    ((t (:foreground ,gray5))))
   `(marginalia-type                   ((t (:foreground ,lack))))
   `(marginalia-version                ((t (:foreground ,gray6))))
   `(marginalia-true                   ((t (:foreground ,green))))
   `(marginalia-false                  ((t (:foreground ,gray5))))
   `(marginalia-null                   ((t (:foreground ,gray5))))
    `(marginalia-char                   ((t (:foreground ,gray7))))
   `(marginalia-list                   ((t (:foreground ,gray7))))
    `(marginalia-function               ((t (:foreground ,luster))))
    `(marginalia-variable               ((t (:foreground ,blue))))
    `(marginalia-lighter                ((t (:foreground ,gray6))))
    `(marginalia-archive                ((t (:foreground ,yellow))))
    `(marginalia-file-priv-rare         ((t (:foreground ,orange))))
    `(marginalia-installed              ((t (:foreground ,green))))
    `(marginalia-value                  ((t (:foreground ,gray7))))

   ;; ---- Orderless match groups (used by orderless completion style) ----
   `(orderless-match-face-0            ((t (:foreground ,luster :weight bold))))
   `(orderless-match-face-1            ((t (:foreground ,lack   :weight bold))))
   `(orderless-match-face-2            ((t (:foreground ,green  :weight bold))))
   `(orderless-match-face-3            ((t (:foreground ,blue   :weight bold))))

   ;; ---- Consult (preview, narrow indicator, line/file-match faces) ----
    `(consult-preview-line              ((t (:background ,gray1 :extend t))))
    `(consult-highlight-match           ((t (:inherit match))))
    `(consult-highlight-mark            ((t (:foreground ,bg :background ,orange))))
    `(consult-preview-match             ((t (:inherit match))))
    `(consult-preview-insertion         ((t (:foreground ,bg :background ,green))))
    `(consult-preview-cursor            ((t (:inherit cursor))))
   `(consult-line-number               ((t (:foreground ,gray5))))
   `(consult-line-number-prefix        ((t (:foreground ,gray5))))
   `(consult-line-number-wrapped       ((t (:foreground ,gray5))))
   `(consult-file                      ((t (:foreground ,gray7))))
   `(consult-bookmark                  ((t (:foreground ,lack))))
   `(consult-buffer                    ((t (:foreground ,gray7))))
   `(consult-narrow-indicator          ((t (:foreground ,orange))))
    `(consult-async-running             ((t (:foreground ,orange))))
    `(consult-async-finished            ((t (:foreground ,green))))
    `(consult-async-failed              ((t (:foreground ,red))))
    `(consult-async-split               ((t (:foreground ,orange))))
    `(consult-async-option              ((t (:foreground ,gray6))))
    `(consult-grep-context              ((t (:foreground ,gray6))))
    `(consult-help                      ((t (:foreground ,gray6))))
    `(consult-key                       ((t (:foreground ,lack))))
    `(consult-imenu-prefix              ((t (:foreground ,gray5))))

   ;; ---- Nerd icons (semantic categories: keep monochrome-ish) ----
   `(nerd-icons-blue                   ((t (:foreground ,lack))))
   `(nerd-icons-blue-alt               ((t (:foreground ,lack))))
   `(nerd-icons-cyan                   ((t (:foreground ,lack))))
   `(nerd-icons-cyan-alt               ((t (:foreground ,lack))))
   `(nerd-icons-dblue                  ((t (:foreground ,gray6))))
   `(nerd-icons-dcyan                  ((t (:foreground ,gray6))))
   `(nerd-icons-dgreen                 ((t (:foreground ,green))))
   `(nerd-icons-dmaroon                ((t (:foreground ,gray6))))
   `(nerd-icons-dorange                ((t (:foreground ,orange))))
   `(nerd-icons-dpink                  ((t (:foreground ,gray6))))
   `(nerd-icons-dpurple                ((t (:foreground ,lack))))
   `(nerd-icons-dred                   ((t (:foreground ,red))))
   `(nerd-icons-dsilver                ((t (:foreground ,gray6))))
   `(nerd-icons-dyellow                ((t (:foreground ,yellow))))
   `(nerd-icons-green                  ((t (:foreground ,green))))
   `(nerd-icons-lblue                  ((t (:foreground ,lack))))
   `(nerd-icons-lcyan                  ((t (:foreground ,lack))))
   `(nerd-icons-lgreen                 ((t (:foreground ,green))))
   `(nerd-icons-lmaroon                ((t (:foreground ,gray7))))
   `(nerd-icons-lorange                ((t (:foreground ,orange))))
   `(nerd-icons-lpink                  ((t (:foreground ,gray7))))
   `(nerd-icons-lpurple                ((t (:foreground ,lack))))
   `(nerd-icons-lred                   ((t (:foreground ,red))))
   `(nerd-icons-lsilver                ((t (:foreground ,gray7))))
   `(nerd-icons-lyellow                ((t (:foreground ,yellow))))
   `(nerd-icons-maroon                 ((t (:foreground ,gray7))))
   `(nerd-icons-orange                 ((t (:foreground ,orange))))
   `(nerd-icons-pink                   ((t (:foreground ,gray7))))
   `(nerd-icons-purple                 ((t (:foreground ,lack))))
   `(nerd-icons-purple-alt             ((t (:foreground ,lack))))
   `(nerd-icons-red                    ((t (:foreground ,red))))
   `(nerd-icons-red-alt                ((t (:foreground ,red))))
   `(nerd-icons-silver                 ((t (:foreground ,gray7))))
   `(nerd-icons-yellow                 ((t (:foreground ,yellow))))

   ;; ---- Which-key ----
   `(which-key-key-face                ((t (:foreground ,lack))))
   `(which-key-command-description-face  ((t (:foreground ,gray7))))
   `(which-key-local-map-description-face ((t (:foreground ,gray7))))
   `(which-key-group-description-face  ((t (:foreground ,luster))))
   `(which-key-separator-face          ((t (:foreground ,gray4))))
    `(which-key-special-key-face        ((t (:foreground ,lack))))
    `(which-key-note-face               ((t (:foreground ,gray6))))
    `(which-key-docstring-face          ((t (:foreground ,gray6))))
    `(which-key-highlighted-command-face ((t (:foreground ,luster :weight bold))))

   ;; ---- Search / isearch ----
   `(isearch                           ((t (:foreground ,bg :background ,gray8 :weight bold))))
   `(isearch-fail                      ((t (:foreground ,bg :background ,red :weight bold))))
   `(isearch-group-1                   ((t (:foreground ,bg :background ,lack))))
   `(isearch-group-2                   ((t (:foreground ,bg :background ,blue))))
   `(lazy-highlight                    ((t (:foreground ,bg :background ,lack))))
   `(query-replace                     ((t (:foreground ,bg :background ,orange))))
   `(highlight-symbol-face             ((t (:background ,gray2))))
   `(show-paren-match                  ((t (:background ,gray4 :weight bold))))
   `(show-paren-match-expression       ((t (:background ,gray2))))
   `(show-paren-mismatch               ((t (:foreground ,bg :background ,red :weight bold))))

   ;; ---- Diff / diff-mode / ediff / smerge / diff-hl ----
   `(diff-header                       ((t (:foreground ,gray7 :background ,gray1))))
   `(diff-file-header                  ((t (:foreground ,luster :background ,gray1 :weight bold))))
   `(diff-hunk-header                  ((t (:foreground ,gray6 :background ,gray2))))
   `(diff-function                     ((t (:foreground ,gray6))))
   `(diff-context                      ((t (:foreground ,gray7))))
    `(diff-added                        ((t (:foreground ,green :background ,gray1 :extend t))))
    `(diff-removed                      ((t (:foreground ,orange :background ,gray1 :extend t))))
    `(diff-changed                      ((t (:foreground ,blue :background ,gray1 :extend t))))
    `(diff-changed-unspecified          ((t (:foreground ,blue :background ,gray1 :extend t))))
   `(diff-refine-added                 ((t (:foreground ,green :background ,gray2 :weight bold))))
   `(diff-refine-removed               ((t (:foreground ,orange :background ,gray2 :weight bold))))
   `(diff-refine-changed               ((t (:foreground ,blue :background ,gray2 :weight bold))))
   `(diff-indicator-added              ((t (:foreground ,green))))
   `(diff-indicator-removed            ((t (:foreground ,orange))))
   `(diff-indicator-changed            ((t (:foreground ,blue))))
   `(diff-nonexistent                  ((t (:foreground ,gray4))))
   `(smerge-upper                      ((t (:background ,gray2))))
   `(smerge-lower                      ((t (:background ,gray2))))
   `(smerge-base                       ((t (:background ,gray1))))
   `(smerge-markers                    ((t (:foreground ,orange :background ,gray2))))
   `(smerge-refined-added              ((t (:inherit diff-refine-added))))
   `(smerge-refined-removed            ((t (:inherit diff-refine-removed))))
   `(diff-hl-insert                    ((t (:foreground ,green :background ,bg))))
   `(diff-hl-delete                    ((t (:foreground ,orange :background ,bg))))
   `(diff-hl-change                    ((t (:foreground ,blue :background ,bg))))
   `(diff-hl-margin-insert             ((t (:foreground ,green))))
   `(diff-hl-margin-delete             ((t (:foreground ,orange))))
   `(diff-hl-margin-change             ((t (:foreground ,blue))))

   ;; ---- Magit ----
   `(magit-section-heading             ((t (:foreground ,luster :weight bold))))
    `(magit-section-heading-selection   ((t (:foreground ,luster :background ,gray2))))
    `(magit-section-highlight           ((t (:background ,gray1))))
    `(magit-section-secondary-heading   ((t (:foreground ,gray7))))
    `(magit-section-child-count         ((t (:foreground ,gray5))))
    `(magit-left-margin                 ((t (:foreground ,gray5 :background ,bg))))
    `(magit-header-line                 ((t (:foreground ,luster :background ,bg-statusln :weight bold))))
    `(magit-header-line-key             ((t (:foreground ,lack :weight bold))))
    `(magit-header-line-log-select      ((t (:foreground ,luster :background ,bg-statusln :weight bold))))
    `(magit-branch-current              ((t (:foreground ,luster :weight bold :box (:line-width -1 :color ,gray4)))))
    `(magit-branch-local                ((t (:foreground ,lack))))
    `(magit-branch-remote               ((t (:foreground ,green))))
    `(magit-branch-remote-head          ((t (:foreground ,green :weight bold))))
    `(magit-branch-upstream             ((t (:foreground ,gray6))))
    `(magit-branch-warning              ((t (:foreground ,orange :weight bold))))
    `(magit-head                        ((t (:foreground ,luster :weight bold))))
    `(magit-refname                     ((t (:foreground ,gray7))))
    `(magit-refname-stash               ((t (:foreground ,gray6 :slant italic))))
    `(magit-refname-wip                 ((t (:foreground ,gray6 :slant italic))))
    `(magit-refname-pullreq             ((t (:foreground ,lack))))
    `(magit-tag                         ((t (:foreground ,yellow))))
    `(magit-hash                        ((t (:foreground ,gray5))))
    `(magit-filename                    ((t (:foreground ,gray8))))
   `(magit-log-author                  ((t (:foreground ,gray7))))
   `(magit-log-date                    ((t (:foreground ,gray5))))
   `(magit-log-graph                   ((t (:foreground ,gray4))))
   `(magit-dimmed                      ((t (:foreground ,gray5))))
    `(magit-diff-added                  ((t (:foreground ,green :background ,gray1 :extend t))))
    `(magit-diff-added-highlight        ((t (:foreground ,green :background ,gray2 :extend t))))
    `(magit-diff-removed                ((t (:foreground ,orange :background ,gray1 :extend t))))
    `(magit-diff-removed-highlight      ((t (:foreground ,orange :background ,gray2 :extend t))))
    `(magit-diff-context                ((t (:foreground ,gray6 :background ,bg :extend t))))
    `(magit-diff-context-highlight      ((t (:foreground ,gray7 :background ,gray1 :extend t))))
    `(magit-diff-base                   ((t (:foreground ,yellow :background ,gray1 :extend t))))
    `(magit-diff-base-highlight         ((t (:foreground ,yellow :background ,gray2 :extend t))))
   `(magit-diff-hunk-heading           ((t (:foreground ,gray7 :background ,gray2))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,luster :background ,gray3))))
   `(magit-diff-hunk-heading-selection ((t (:foreground ,luster :background ,gray3 :weight bold))))
    `(magit-diff-file-heading           ((t (:foreground ,luster :weight bold))))
    `(magit-diff-file-heading-highlight ((t (:foreground ,luster :background ,gray1 :weight bold))))
    `(magit-diff-file-heading-selection ((t (:foreground ,luster :background ,gray2 :weight bold))))
    `(magit-diff-hunk-region            ((t (:weight bold))))
    `(magit-diff-lines-heading          ((t (:foreground ,luster :background ,gray3))))
    `(magit-diff-lines-boundary         ((t (:inherit magit-diff-lines-heading))))
    `(magit-diff-conflict-heading       ((t (:foreground ,orange :background ,gray2 :weight bold))))
    `(magit-diff-conflict-heading-highlight ((t (:foreground ,luster :background ,gray3 :weight bold))))
    `(magit-diff-our                    ((t (:foreground ,orange :background ,gray1 :extend t))))
    `(magit-diff-our-highlight          ((t (:foreground ,orange :background ,gray2 :extend t :weight bold))))
    `(magit-diff-their                  ((t (:foreground ,green :background ,gray1 :extend t))))
    `(magit-diff-their-highlight        ((t (:foreground ,green :background ,gray2 :extend t :weight bold))))
    `(magit-diff-revision-summary       ((t (:foreground ,gray7))))
    `(magit-diff-revision-summary-highlight ((t (:foreground ,luster :background ,gray2))))
    `(magit-diff-whitespace-warning     ((t (:inherit trailing-whitespace))))
   `(magit-diffstat-added              ((t (:foreground ,green))))
   `(magit-diffstat-removed            ((t (:foreground ,orange))))
    `(magit-process-ok                  ((t (:foreground ,green))))
    `(magit-process-ng                  ((t (:foreground ,red))))
    `(magit-mode-line-process           ((t (:foreground ,orange))))
    `(magit-mode-line-process-error     ((t (:foreground ,red :weight bold))))
   `(magit-bisect-good                 ((t (:foreground ,green))))
   `(magit-bisect-bad                  ((t (:foreground ,red))))
   `(magit-bisect-skip                 ((t (:foreground ,gray5))))
    `(magit-blame-heading               ((t (:foreground ,gray7 :background ,gray2))))
    `(magit-blame-highlight             ((t (:foreground ,luster :background ,gray2 :extend t))))
    `(magit-blame-margin                ((t (:foreground ,gray6 :background ,gray2))))
    `(magit-blame-dimmed                ((t (:foreground ,gray5 :background ,gray1))))
    `(magit-blame-summary               ((t (:foreground ,gray7))))
   `(magit-blame-hash                  ((t (:foreground ,gray5))))
   `(magit-blame-name                  ((t (:foreground ,lack))))
   `(magit-blame-date                  ((t (:foreground ,gray5))))
    `(magit-cherry-equivalent           ((t (:foreground ,green))))
    `(magit-cherry-unmatched            ((t (:foreground ,orange))))
    `(magit-sequence-pick               ((t (:foreground ,gray7))))
    `(magit-sequence-stop               ((t (:foreground ,orange :weight bold))))
    `(magit-sequence-part               ((t (:foreground ,yellow))))
    `(magit-sequence-head               ((t (:foreground ,luster :weight bold))))
    `(magit-sequence-drop               ((t (:foreground ,red :strike-through t))))
    `(magit-sequence-done               ((t (:foreground ,gray5))))
    `(magit-sequence-onto               ((t (:foreground ,lack))))
    `(magit-sequence-exec               ((t (:foreground ,green))))
   `(magit-keyword                     ((t (:foreground ,lack))))
   `(magit-keyword-squash              ((t (:foreground ,orange))))
   `(magit-reflog-amend                ((t (:foreground ,orange))))
   `(magit-reflog-checkout             ((t (:foreground ,lack))))
   `(magit-reflog-cherry-pick          ((t (:foreground ,green))))
   `(magit-reflog-commit               ((t (:foreground ,green))))
   `(magit-reflog-merge                ((t (:foreground ,green))))
   `(magit-reflog-other                ((t (:foreground ,gray6))))
   `(magit-reflog-rebase               ((t (:foreground ,orange))))
   `(magit-reflog-remote               ((t (:foreground ,lack))))
   `(magit-reflog-reset                ((t (:foreground ,red))))
   `(magit-signature-good              ((t (:foreground ,green))))
   `(magit-signature-bad               ((t (:foreground ,red))))
    `(magit-signature-untrusted         ((t (:foreground ,orange))))
    `(magit-signature-expired           ((t (:foreground ,orange))))
    `(magit-signature-expired-key       ((t (:foreground ,orange :slant italic))))
    `(magit-signature-revoked           ((t (:foreground ,red))))
    `(magit-signature-error             ((t (:foreground ,red))))
    `(magit-popup-disabled-argument     ((t (:foreground ,gray4))))
    `(magit-popup-option-value          ((t (:foreground ,gray7))))

    ;; ---- Transient (Magit popups) ----
    `(transient-heading                 ((t (:foreground ,luster :weight bold))))
    `(transient-key                     ((t (:foreground ,lack :weight bold))))
    `(transient-key-stay                ((t (:foreground ,green :weight bold))))
    `(transient-key-noop                ((t (:foreground ,gray4))))
    `(transient-key-return              ((t (:foreground ,yellow :weight bold))))
    `(transient-key-recurse             ((t (:foreground ,blue :weight bold))))
    `(transient-key-stack               ((t (:foreground ,orange :weight bold))))
    `(transient-key-exit                ((t (:foreground ,red :weight bold))))
    `(transient-unreachable-key         ((t (:foreground ,gray4))))
    `(transient-nonstandard-key         ((t (:box (:line-width -1 :color ,gray4)))))
    `(transient-mismatched-key          ((t (:box (:line-width -1 :color ,orange)))))
    `(transient-argument                ((t (:foreground ,gray8 :weight bold))))
    `(transient-inactive-argument       ((t (:foreground ,gray5))))
    `(transient-inapt-argument          ((t (:foreground ,gray4 :slant italic))))
    `(transient-value                   ((t (:foreground ,gray7 :weight bold))))
    `(transient-inactive-value          ((t (:foreground ,gray5))))
    `(transient-delimiter               ((t (:foreground ,gray4))))
    `(transient-active-infix            ((t (:foreground ,luster :background ,gray2 :weight bold))))
    `(transient-enabled-suffix          ((t (:foreground ,bg :background ,green :weight bold))))
    `(transient-disabled-suffix         ((t (:foreground ,bg :background ,red :weight bold))))
    `(transient-higher-level            ((t (:box (:line-width -1 :color ,gray4)))))
    `(transient-unreachable             ((t (:foreground ,gray4))))
    `(transient-inapt-suffix            ((t (:foreground ,gray4 :slant italic))))

    ;; ---- Forge ----
    `(forge-dimmed                      ((t (:foreground ,gray5))))
    `(forge-topic-header-line           ((t (:inherit magit-header-line))))
    `(forge-discussion-answer-heading   ((t (:foreground ,green :background ,gray1 :weight bold))))
    `(forge-topic-slug-open             ((t (:foreground ,gray5))))
    `(forge-topic-slug-realized         ((t (:foreground ,gray5))))
    `(forge-topic-slug-expunged         ((t (:foreground ,gray4 :strike-through t))))
    `(forge-topic-slug-saved            ((t (:foreground ,orange))))
    `(forge-topic-slug-unread           ((t (:foreground ,luster :weight bold))))
    `(forge-topic-unread                ((t (:foreground ,luster :weight bold :box (:line-width -1 :color ,gray4)))))
    `(forge-topic-pending               ((t (:foreground ,orange :weight bold))))
    `(forge-topic-done                  ((t (:foreground ,gray6))))
    `(forge-discussion-open             ((t (:foreground ,gray8 :slant italic))))
    `(forge-discussion-completed        ((t (:foreground ,gray5 :slant italic))))
    `(forge-discussion-expunged         ((t (:foreground ,gray4 :slant italic :strike-through t))))
    `(forge-issue-open                  ((t (:foreground ,gray8))))
    `(forge-issue-completed             ((t (:foreground ,gray5))))
    `(forge-issue-expunged              ((t (:foreground ,gray4 :strike-through t))))
    `(forge-pullreq-open                ((t (:foreground ,green))))
    `(forge-pullreq-merged              ((t (:foreground ,lack :weight bold))))
    `(forge-pullreq-rejected            ((t (:foreground ,orange :strike-through t))))
    `(forge-pullreq-draft               ((t (:foreground ,gray6 :background ,gray1 :slant italic))))
    `(forge-topic-label                 ((t (:foreground ,gray7 :background ,gray2 :box (:line-width -1 :color ,gray4)))))
    `(forge-post-author                 ((t (:foreground ,luster :weight bold))))
    `(forge-post-date                   ((t (:foreground ,gray5 :slant italic))))
    `(forge-suffix-active               ((t (:foreground ,green))))
    `(forge-suffix-implied              ((t (:foreground ,gray6))))
    `(forge-suffix-active-and-implied   ((t (:foreground ,green :weight bold))))

    ;; ---- Git commit / rebase buffers ----
    `(git-commit-summary                ((t (:foreground ,luster :weight bold))))
    `(git-commit-overlong-summary       ((t (:foreground ,orange :underline (:style wave :color ,orange)))))
    `(git-commit-nonempty-second-line   ((t (:foreground ,red :background ,gray1 :weight bold))))
    `(git-commit-keyword                ((t (:foreground ,lack :weight bold))))
    `(git-commit-trailer-token          ((t (:foreground ,lack))))
    `(git-commit-trailer-value          ((t (:foreground ,gray7))))
    `(git-commit-comment-heading        ((t (:foreground ,gray6 :weight bold))))
    `(git-commit-comment-action         ((t (:foreground ,orange))))
    `(git-commit-comment-file           ((t (:foreground ,gray7))))
    `(git-commit-comment-branch-local   ((t (:foreground ,lack))))
    `(git-commit-comment-branch-remote  ((t (:foreground ,green))))
    `(git-commit-comment-detached       ((t (:foreground ,orange))))
    `(git-rebase-action                 ((t (:foreground ,lack :weight bold))))
    `(git-rebase-killed-action          ((t (:foreground ,red :strike-through t))))
    `(git-rebase-hash                   ((t (:foreground ,gray5))))
    `(git-rebase-label                  ((t (:foreground ,yellow))))
    `(git-rebase-description            ((t (:foreground ,gray7))))
    `(git-rebase-comment-heading        ((t (:foreground ,gray6 :weight bold))))
    `(git-rebase-comment-hash           ((t (:foreground ,gray5))))

   ;; ---- Org-mode ----
    `(org-document-title                ((t (:foreground ,luster :weight bold :height 1.2))))
    `(org-document-info                 ((t (:foreground ,gray7))))
    `(org-document-info-keyword         ((t (:foreground ,gray4))))
    `(org-hide                          ((t (:foreground ,bg))))
    `(org-indent                        ((t (:inherit org-hide))))
    `(org-level-1                       ((t (:foreground ,luster :weight bold))))
   `(org-level-2                       ((t (:foreground ,gray8 :weight bold))))
   `(org-level-3                       ((t (:foreground ,gray7))))
   `(org-level-4                       ((t (:foreground ,gray7))))
   `(org-level-5                       ((t (:foreground ,gray6))))
   `(org-level-6                       ((t (:foreground ,gray6))))
   `(org-level-7                       ((t (:foreground ,gray5))))
   `(org-level-8                       ((t (:foreground ,gray5))))
   `(org-headline-done                 ((t (:foreground ,gray5 :strike-through nil))))
   `(org-headline-todo                 ((t (:foreground ,luster))))
   `(org-todo                          ((t (:foreground ,orange :weight bold))))
   `(org-done                          ((t (:foreground ,gray5 :weight bold))))
   `(org-priority                      ((t (:foreground ,lack :weight bold))))
   `(org-tag                           ((t (:foreground ,gray5))))
   `(org-tag-group                     ((t (:foreground ,gray5))))
   `(org-special-keyword               ((t (:foreground ,gray5))))
   `(org-meta-line                     ((t (:foreground ,gray4))))
   `(org-drawer                        ((t (:foreground ,gray4))))
   `(org-property-value                ((t (:foreground ,gray6))))
   `(org-date                          ((t (:foreground ,lack :underline nil))))
   `(org-scheduled                     ((t (:foreground ,gray7))))
   `(org-scheduled-today               ((t (:foreground ,luster))))
   `(org-scheduled-previously          ((t (:foreground ,orange))))
   `(org-warning                       ((t (:inherit warning))))
   `(org-upcoming-deadline             ((t (:foreground ,orange))))
   `(org-time-grid                     ((t (:foreground ,gray5))))
   `(org-link                          ((t (:inherit link))))
   `(org-footnote                      ((t (:foreground ,lack :underline t))))
    `(org-code                          ((t (:inherit fixed-pitch :foreground ,gray8 :background ,gray1))))
    `(org-verbatim                      ((t (:inherit fixed-pitch :foreground ,gray8 :background ,gray1))))
    `(org-block                         ((t (:inherit fixed-pitch :foreground ,luster :background ,gray1 :extend t))))
    `(org-block-begin-line              ((t (:foreground ,gray4 :background ,gray1 :extend t))))
    `(org-block-end-line                ((t (:foreground ,gray4 :background ,gray1 :extend t))))
    `(org-formula                       ((t (:foreground ,lack))))
    `(org-table                         ((t (:inherit fixed-pitch :foreground ,gray7))))
   `(org-table-header                  ((t (:foreground ,luster :background ,gray2 :weight bold))))
   `(org-checkbox                      ((t (:foreground ,lack :weight bold))))
   `(org-checkbox-statistics-todo      ((t (:foreground ,red))))
   `(org-checkbox-statistics-done      ((t (:foreground ,green))))
   `(org-list-dt                       ((t (:foreground ,luster :weight bold))))
   `(org-quote                         ((t (:foreground ,gray7 :slant italic))))
   `(org-verse                         ((t (:foreground ,gray7 :slant italic))))
   `(org-ellipsis                      ((t (:foreground ,gray4 :underline nil))))
   `(org-agenda-structure              ((t (:foreground ,luster :weight bold))))
   `(org-agenda-date                   ((t (:foreground ,gray7))))
   `(org-agenda-date-today             ((t (:foreground ,luster :weight bold))))
    `(org-agenda-date-weekend           ((t (:foreground ,gray6))))
    `(org-agenda-current-time           ((t (:foreground ,orange))))
    `(org-agenda-done                   ((t (:foreground ,gray5))))
    `(org-agenda-dimmed-todo-face       ((t (:foreground ,gray5))))

    ;; ---- Org-modern ----
    `(org-modern-symbol                 ((t (:foreground ,gray5))))
    `(org-modern-block-name             ((t (:foreground ,gray5 :height 0.9))))
    `(org-modern-progress-complete      ((t (:foreground ,bg :background ,gray7))))
    `(org-modern-progress-incomplete    ((t (:foreground ,gray7 :background ,gray2))))
    `(org-modern-tag                    ((t (:foreground ,gray7 :background ,gray2 :box (:line-width -1 :color ,gray3)))))
    `(org-modern-internal-target        ((t (:foreground ,lack :underline t))))
    `(org-modern-radio-target           ((t (:foreground ,lack :underline t))))
    `(org-modern-done                   ((t (:foreground ,gray5 :background ,gray1 :box (:line-width -1 :color ,gray3)))))
    `(org-modern-todo                   ((t (:foreground ,bg :background ,orange :weight bold :box (:line-width -1 :color ,gray4)))))
    `(org-modern-priority               ((t (:foreground ,bg :background ,lack :weight bold))))
    `(org-modern-date-active            ((t (:foreground ,lack :background ,gray1 :box (:line-width -1 :color ,gray3)))))
    `(org-modern-time-active            ((t (:foreground ,bg :background ,lack :weight bold))))
    `(org-modern-date-inactive          ((t (:foreground ,gray5 :background ,gray1 :box (:line-width -1 :color ,gray2)))))
    `(org-modern-time-inactive          ((t (:foreground ,gray4 :background ,gray2))))
    `(org-modern-horizontal-rule        ((t (:underline ,gray3 :extend t))))
    `(org-modern-habit                  ((t (:background ,gray1))))

   ;; ---- Markdown-mode ----
   `(markdown-header-face              ((t (:weight bold))))
   `(markdown-header-face-1            ((t (:foreground ,luster :weight bold))))
   `(markdown-header-face-2            ((t (:foreground ,gray8 :weight bold))))
   `(markdown-header-face-3            ((t (:foreground ,gray7))))
   `(markdown-header-face-4            ((t (:foreground ,gray7))))
   `(markdown-header-face-5            ((t (:foreground ,gray6))))
   `(markdown-header-face-6            ((t (:foreground ,gray6))))
    `(markdown-header-delimiter-face    ((t (:foreground ,gray4))))
    `(markdown-header-rule-face         ((t (:foreground ,gray4))))
    `(markdown-link-face                ((t (:inherit link))))
    `(markdown-plain-url-face           ((t (:inherit link))))
    `(markdown-url-face                 ((t (:foreground ,gray6))))
    `(markdown-link-title-face          ((t (:foreground ,gray7))))
    `(markdown-inline-code-face         ((t (:foreground ,gray8))))
   `(markdown-pre-face                 ((t (:foreground ,luster :background ,gray1))))
   `(markdown-code-face                ((t (:foreground ,luster :background ,gray1 :extend t))))
   `(markdown-language-keyword-face    ((t (:foreground ,gray4))))
    `(markdown-blockquote-face          ((t (:foreground ,gray6 :slant italic))))
    `(markdown-list-face                ((t (:foreground ,lack))))
    `(markdown-italic-face              ((t (:slant italic))))
    `(markdown-bold-face                ((t (:weight bold))))
    `(markdown-strike-through-face      ((t (:strike-through t))))
    `(markdown-markup-face              ((t (:foreground ,gray4))))
    `(markdown-metadata-key-face        ((t (:foreground ,gray5))))
    `(markdown-metadata-value-face      ((t (:foreground ,gray7))))
    `(markdown-comment-face             ((t (:inherit font-lock-comment-face))))
    `(markdown-footnote-marker-face     ((t (:foreground ,lack :weight bold))))
    `(markdown-footnote-text-face       ((t (:foreground ,gray6))))
    `(markdown-gfm-checkbox-face        ((t (:foreground ,lack :weight bold))))
    `(markdown-highlight-face           ((t (:background ,gray1))))
    `(markdown-highlighting-face        ((t (:background ,gray1))))
    `(markdown-hr-face                  ((t (:foreground ,gray4))))
    `(markdown-html-entity-face         ((t (:foreground ,gray7))))
    `(markdown-language-info-face       ((t (:foreground ,gray6))))
    `(markdown-line-break-face          ((t (:foreground ,orange :underline t))))
    `(markdown-math-face                ((t (:foreground ,gray8))))
    `(markdown-missing-link-face        ((t (:foreground ,red :underline (:style wave :color ,red)))))
    `(markdown-reference-face           ((t (:foreground ,gray6))))
    `(markdown-table-face               ((t (:foreground ,gray7))))
    `(markdown-html-tag-name-face       ((t (:foreground ,lack))))
   `(markdown-html-tag-delimiter-face  ((t (:foreground ,gray5))))
   `(markdown-html-attr-name-face      ((t (:foreground ,blue))))
    `(markdown-html-attr-value-face     ((t (:foreground ,gray7))))

   ;; ---- Eglot / flymake / diagnostics ----
   `(eglot-highlight-symbol-face       ((t (:background ,gray2))))
   `(eglot-inlay-hint-face             ((t (:foreground ,gray5))))
   `(eglot-parameter-hint-face         ((t (:foreground ,gray5))))
   `(eglot-type-hint-face              ((t (:foreground ,gray5))))
   `(eglot-mode-line                   ((t (:foreground ,gray6))))
   `(eglot-diagnostic-tag-unnecessary-face ((t (:foreground ,gray5))))
   `(eglot-diagnostic-tag-deprecated-face  ((t (:strike-through t))))
   `(eldoc-highlight-function-argument ((t (:foreground ,luster :weight bold))))
    `(flymake-error                     ((t (:underline (:style wave :color ,red)))))
    `(flymake-warning                   ((t (:underline (:style wave :color ,orange)))))
    `(flymake-note                      ((t (:underline (:style wave :color ,gray6)))))
    `(flymake-error-echo                ((t (:foreground ,red))))
    `(flymake-warning-echo              ((t (:foreground ,orange))))
    `(flymake-note-echo                 ((t (:foreground ,gray6))))
    `(flyspell-incorrect                ((t (:underline (:style wave :color ,red)))))
    `(flyspell-duplicate                ((t (:underline (:style wave :color ,orange)))))
    `(compilation-error                 ((t (:foreground ,red :weight bold))))
   `(compilation-warning               ((t (:foreground ,orange))))
   `(compilation-info                  ((t (:foreground ,gray6))))
   `(compilation-line-number           ((t (:foreground ,gray5))))
   `(compilation-column-number         ((t (:foreground ,gray5))))
   `(compilation-mode-line-exit        ((t (:foreground ,green))))
   `(compilation-mode-line-fail        ((t (:foreground ,red))))
    `(compilation-mode-line-run         ((t (:foreground ,orange))))
    `(xref-file-header                  ((t (:foreground ,luster :weight bold))))
    `(xref-line-number                  ((t (:foreground ,gray5))))
    `(xref-match                        ((t (:inherit match))))
    `(grep-context-face                 ((t (:foreground ,gray6))))
    `(grep-error-face                   ((t (:foreground ,red :weight bold))))
    `(grep-hit-face                     ((t (:foreground ,gray7))))
    `(grep-match-face                   ((t (:inherit match))))

    ;; ---- Evil / avy / embark ----
    `(evil-ex-commands                  ((t (:foreground ,lack))))
    `(evil-ex-info                      ((t (:foreground ,gray7))))
   `(evil-ex-substitute-matches        ((t (:foreground ,bg :background ,lack))))
   `(evil-ex-substitute-replacement    ((t (:foreground ,green :underline t))))
   `(evil-ex-search                    ((t (:inherit isearch))))
   `(evil-ex-lazy-highlight            ((t (:inherit lazy-highlight))))
   `(evil-search-highlight-persist-highlight-face ((t (:inherit lazy-highlight))))
   `(avy-lead-face                     ((t (:foreground ,bg :background ,orange :weight bold))))
   `(avy-lead-face-0                   ((t (:foreground ,bg :background ,luster :weight bold))))
   `(avy-lead-face-1                   ((t (:foreground ,bg :background ,gray6 :weight bold))))
    `(avy-lead-face-2                   ((t (:foreground ,bg :background ,lack :weight bold))))
    `(avy-goto-char-timer-face          ((t (:foreground ,bg :background ,orange :weight bold))))
    `(avy-background-face               ((t (:foreground ,gray4))))
    `(embark-keybinding                 ((t (:foreground ,lack))))
    `(embark-keybinding-repeat          ((t (:foreground ,orange))))
    `(embark-keymap                     ((t (:foreground ,gray7 :slant italic))))
    `(embark-target                     ((t (:foreground ,luster :weight bold))))
    `(embark-collect-marked             ((t (:background ,gray2))))
    `(embark-verbose-indicator-title    ((t (:foreground ,luster :weight bold))))
    `(embark-verbose-indicator-documentation ((t (:foreground ,gray6))))
    `(embark-verbose-indicator-shadowed ((t (:foreground ,gray5))))
    `(embark-collect-candidate          ((t (:inherit default))))
    `(embark-collect-annotation         ((t (:foreground ,gray6))))
    `(embark-collect-group-title        ((t (:foreground ,luster :weight bold))))
    `(embark-collect-group-separator    ((t (:foreground ,gray3 :strike-through ,gray3))))
    `(embark-selected                   ((t (:inherit match))))

   ;; ---- Tab-bar / tab-line ----
   `(tab-bar                           ((t (:foreground ,gray7 :background ,bg-statusln :box nil))))
   `(tab-bar-tab                       ((t (:foreground ,luster :background ,bg :box (:line-width 1 :color ,gray3)))))
   `(tab-bar-tab-inactive              ((t (:foreground ,gray6 :background ,bg-statusln :box nil))))
   `(tab-bar-tab-ungrouped             ((t (:foreground ,gray6 :background ,bg-statusln))))
   `(tab-bar-tab-group-current         ((t (:foreground ,luster :background ,bg :weight bold))))
   `(tab-bar-tab-group-inactive        ((t (:foreground ,gray6 :background ,bg-statusln))))
   `(tab-line                          ((t (:foreground ,gray7 :background ,bg-statusln))))
   `(tab-line-tab                      ((t (:foreground ,luster :background ,bg))))
   `(tab-line-tab-current              ((t (:foreground ,luster :background ,bg :weight bold))))
   `(tab-line-tab-inactive             ((t (:foreground ,gray6 :background ,bg-statusln))))
   `(tab-line-tab-modified             ((t (:foreground ,orange))))
   `(tab-line-highlight                ((t (:background ,gray3))))

   ;; ---- Dired ----
   `(dired-header                      ((t (:foreground ,luster :weight bold))))
   `(dired-directory                   ((t (:foreground ,lack :weight bold))))
   `(dired-symlink                     ((t (:foreground ,green :slant italic))))
   `(dired-broken-symlink              ((t (:foreground ,red :slant italic))))
   `(dired-special                     ((t (:foreground ,orange))))
   `(dired-perm-write                  ((t (:foreground ,orange))))
   `(dired-flagged                     ((t (:foreground ,red :weight bold))))
   `(dired-marked                      ((t (:foreground ,yellow :weight bold))))
   `(dired-mark                        ((t (:foreground ,yellow))))
   `(dired-ignored                     ((t (:foreground ,gray4))))

   ;; ---- Info / help ----
   `(info-title-1                      ((t (:foreground ,luster :weight bold))))
   `(info-title-2                      ((t (:foreground ,gray8 :weight bold))))
   `(info-title-3                      ((t (:foreground ,gray7))))
   `(info-title-4                      ((t (:foreground ,gray7))))
   `(info-menu-header                  ((t (:foreground ,luster :weight bold))))
   `(info-menu-star                    ((t (:foreground ,lack))))
   `(info-node                         ((t (:foreground ,lack :slant italic))))
   `(info-xref                         ((t (:inherit link))))
   `(info-xref-visited                 ((t (:inherit link-visited))))
   `(info-quoted-name                  ((t (:foreground ,lack))))
    `(info-string                       ((t (:foreground ,gray7))))
   `(help-key-binding                  ((t (:foreground ,lack :background ,gray1 :box (:line-width -1 :color ,gray3)))))
   `(help-argument-name                ((t (:foreground ,blue :slant italic))))
   `(help-for-help-header              ((t (:foreground ,luster :weight bold))))

   ;; ---- Whitespace mode ----
   `(whitespace-line                   ((t (:background ,bg-whitespace))))
   `(whitespace-empty                  ((t (:background ,bg-whitespace))))
   `(whitespace-indentation            ((t (:foreground ,gray3))))
   `(whitespace-big-indent             ((t (:foreground ,orange :background ,bg-whitespace))))
   `(whitespace-hspace                 ((t (:foreground ,gray3))))
   `(whitespace-space-after-tab        ((t (:foreground ,orange))))
   `(whitespace-space-before-tab       ((t (:foreground ,orange))))

   ;; ---- Fill column / display-line-numbers extras ----
   `(fill-column-indicator             ((t (:foreground ,gray2))))
   `(display-line-numbers              ((t (:inherit line-number))))

    ;; ---- Hl-todo (TODO/FIXME/XXX highlighters) ----
    `(hl-todo                           ((t (:foreground ,orange :background ,gray1 :weight bold :box (:line-width -1 :color ,gray3)))))
    `(hl-todo-flymake-type              ((t (:foreground ,orange :weight bold))))

    ;; ---- solaire-mode ----
    `(solaire-default-face              ((t (:inherit default :background ,gray1))))
    `(solaire-fringe-face               ((t (:inherit fringe :background ,gray1))))
    `(solaire-line-number-face          ((t (:inherit line-number :background ,gray1))))
    `(solaire-header-line-face          ((t (:inherit header-line :background ,gray2))))
    `(solaire-minibuffer-face           ((t (:inherit default :background ,gray2))))
    `(solaire-hl-line-face              ((t (:inherit hl-line :background ,gray2))))
    `(solaire-region-face               ((t (:inherit region))))
    `(solaire-mode-line-face            ((t (:inherit mode-line :background ,gray2))))
    `(solaire-mode-line-active-face     ((t (:inherit mode-line :background ,gray2))))
    `(solaire-mode-line-inactive-face   ((t (:inherit mode-line-inactive :background ,gray1))))
    `(solaire-org-hide-face             ((t (:inherit org-hide :background ,gray1))))

    ;; ---- Tempel ----
    `(tempel-field                      ((t (:foreground ,luster :background ,gray2))))
    `(tempel-form                       ((t (:foreground ,green :background ,gray1))))
    `(tempel-default                    ((t (:foreground ,lack :background ,gray1 :slant italic))))

   ;; ---- Widget ----
   `(widget-field                      ((t (:background ,gray2 :foreground ,luster))))
   `(widget-single-line-field          ((t (:background ,gray2 :foreground ,luster))))
   `(widget-button                     ((t (:foreground ,lack :weight bold))))
   `(widget-button-pressed             ((t (:foreground ,luster))))
   `(widget-documentation              ((t (:foreground ,gray6))))
   `(widget-inactive                   ((t (:foreground ,gray5))))

   ;; ---- Custom (M-x customize) ----
   `(custom-button                     ((t (:foreground ,gray8 :background ,gray2 :box (:line-width 1 :color ,gray4)))))
   `(custom-button-pressed             ((t (:foreground ,luster :background ,gray3 :box (:line-width 1 :color ,gray5)))))
   `(custom-changed                    ((t (:foreground ,orange))))
   `(custom-comment                    ((t (:foreground ,yellow))))
   `(custom-comment-tag                ((t (:foreground ,gray5))))
   `(custom-group-tag                  ((t (:foreground ,luster :weight bold))))
   `(custom-group-tag-1                ((t (:foreground ,gray8 :weight bold))))
   `(custom-modified                   ((t (:foreground ,orange))))
   `(custom-saved                      ((t (:foreground ,green))))
   `(custom-set                        ((t (:foreground ,green))))
   `(custom-state                      ((t (:foreground ,gray6))))
   `(custom-themed                     ((t (:foreground ,lack))))
   `(custom-variable-tag               ((t (:foreground ,blue))))
   `(custom-visibility                 ((t (:foreground ,lack))))

   ;; ---- envrc ----
   `(envrc-mode-line-on-face           ((t (:foreground ,green))))
   `(envrc-mode-line-error-face        ((t (:foreground ,red))))
   `(envrc-mode-line-updating-face     ((t (:foreground ,orange))))
   `(envrc-mode-line-none-face         ((t (:foreground ,gray5)))))

  ;; expose palette symbols for use elsewhere
  (custom-theme-set-variables
   'noir
   '(frame-background-mode 'dark)))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'noir)
(provide 'noir-theme)

;;; noir-theme.el ends here
